name: Orbit Web Login

on: 
  pull_request:
  schedule:
    - cron: '0 5 * * *'  
  
jobs:
  cypress-run:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, windows-latest, macOs-latest]
       
    steps:
      - uses: actions/checkout@v2
        
      - name: Install a project with a clean slate
        run: |
          npm ci
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
        
      - name: Run Orbit Web Login Test (Prod.)
        run: npm run cy:run
